6569 uppersecondary school study progress table Pyramus
otavanopisto/pyramus pull request #1498
Opened 2023-08-17 06:06 UTC by saaralepisto

https://github.com/otavanopisto/muikku/pull/6625

2023-09-01 06:54 UTC, aviljakaine commented on rest/src/main/java/fi/otavanopisto/pyramus/rest/StudentRESTService.java
> +  @RESTPermit(StudentPermissions.LIST_STUDENT_SUBJECT_CHOICES)
Does the student need to be able to load their own choices? If so, this needs to move to an inline check where the ownership is checked separately.

2023-09-04 11:18 UTC, aviljakaine requested changes
Some cleanup

2023-09-04 11:18 UTC, aviljakaine commented on rest/src/main/java/fi/otavanopisto/pyramus/rest/StudentRESTService.java
> +    if (!restSecurity.hasPermission(new String[] { StudentPermissions.FIND_STUDENT, UserPermissions.USER_OWNER }, student, Style.OR)) {
This check is already inside `checkStudent` method so not needed again.

2023-09-04 11:18 UTC, aviljakaine commented on rest/src/main/java/fi/otavanopisto/pyramus/rest/StudentRESTService.java
> +    StaffMember staffMember = userController.findStaffMemberById(sessionController.getUser().getId());
I would drop this and replace the
`if (staffMember != null){` below with
```
if (loggedUser instanceof StaffMember) {
  StaffMember staffMember = (StaffMember) loggedUser;
  ...
```

2023-09-05 05:53 UTC, aviljakaine approved these changes
Looks good to me

2023-09-20 08:54 UTC, pkukkon approved these changes

2023-12-19 08:06 UTC, pkukkon approved these changes
Seems okay but TEACHER to CREATE_COURSESTUDENT permission requires that role to be checked in the Pyramus permission matrix (remind everyone to do this after merging to develop).

2024-01-08 07:40 UTC, aviljakaine approved these changes

2024-01-08 07:40 UTC, merged