Multirole
otavanopisto/pyramus pull request #1518
Opened 2023-10-25 07:42 UTC by aviljakaine

2023-10-27 05:23 UTC, pkukkon submitted a review, later dismissed

2024-01-11 07:41 UTC, saaralepisto requested changes
Db script version is already in use, otherwise seems ok

2024-01-23 08:32 UTC, pkukkon approved these changes

2024-01-24 07:47 UTC, pkukkon approved these changes

2024-01-24 07:48 UTC, merged