Parentingrole
otavanopisto/pyramus pull request #1537
Opened 2024-01-24 13:13 UTC by aviljakaine

Closes #1341

2024-01-31 05:11 UTC, pkukkon requested changes

2024-02-01 08:07 UTC, aviljakaine commented on pyramus/src/main/java/fi/otavanopisto/pyramus/json/studentparents/EditStudentParentJSONRequestController.java
> +    String[] roleSelections = StringUtils.isNotBlank(requestContext.getString("role")) ? requestContext.getString("role").split(",") : new String[0];
True, removed this

2024-02-01 08:08 UTC, aviljakaine commented on pyramus/src/main/java/fi/otavanopisto/pyramus/json/studentparents/EditStudentParentJSONRequestController.java
> +//    if (staffMember.getOrganization() != null) {
Reinstated the check, originally parents didn't have organization but it was added later so the check is now valid too

2024-03-12 05:44 UTC, pkukkon approved these changes

2024-04-23 08:52 UTC, merged