Slice: Tietojen valitus muikulle
otavanopisto/pyramus pull request #1559
Opened 2024-03-21 04:57 UTC by saaralepisto

closes #1545

2024-03-26 07:54 UTC, pkukkon requested changes
Minor changes and stuff to be checked.

2024-03-26 07:54 UTC, pkukkon commented on pyramus/src/main/webapp/templates/students/editstudent.jsp
> +                  <c:set var="studentCard" value="${studentCards[student.id]}" />
Does this really work? If the student doesn't have a card, wouldn't accessing this variable later on cause crashes?

2024-03-26 07:54 UTC, pkukkon commented on pyramus/src/main/webapp/templates/students/viewstudent.jsp
> +                        <c:when test="${!empty studentCards[student.id].type}">
Same as before; what if `studentCards[student.id]` is null?

2024-03-26 07:54 UTC, pkukkon commented on persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/students/StudentCard.java
> +  @NotNull
While student technically should always exist, don't use @NotNull for relations as it might confuse Hibernate persistence.

2024-03-26 07:54 UTC, pkukkon commented on rest/src/main/java/fi/otavanopisto/pyramus/rest/StudentRESTService.java
> +      if (!loggedUser.getId().equals(student.getId()) && !loggedUser.hasRole(Role.ADMINISTRATOR)) {
What about administrator access? Isn't this endpoint for students themselves only?

2024-03-26 07:54 UTC, pkukkon commented on rest/src/main/java/fi/otavanopisto/pyramus/rest/StudentRESTService.java
> +    Student student = studentController.findStudentById(loggedUser.getId());
Fetching student and then checking its id seems unnecessary; couldn't you just compare `studentId` to the id of the logged user?

2024-04-10 05:27 UTC, aviljakaine requested changes
Kommentit muutoksista tämän ja edeltävän Slice-pr:n muutoksista.

2024-04-10 05:27 UTC, aviljakaine commented on rest-model/src/main/java/fi/otavanopisto/pyramus/rest/model/StudentCard.java
> +    // TODO Auto-generated constructor stub
Turha todo

2024-04-10 05:27 UTC, aviljakaine commented on rest/src/main/java/fi/otavanopisto/pyramus/rest/ObjectFactory.java
> +              student.getStudyProgramme().getName(),
StudyProgramme tuskin on koskaan null, mutta ehkä sen voisi tsekata samoin kuin typen tuossa yläpuolella.

2024-04-10 05:27 UTC, aviljakaine commented on rest/src/main/java/fi/otavanopisto/pyramus/rest/StudentRESTService.java
> +      response.setId(studentCard.getId());
Alla PUT käyttää jo objectMapperia muodostamaan rest-modelin StudentCard:lle, tässä voisi käyttää samaa `return Response.ok().entity(objectFactory.createModel(...`

Jos korttia ei ole niin pitäisikö palauttaa vain status NOT_FOUND?

2024-04-10 05:27 UTC, aviljakaine commented on rest/src/main/java/fi/otavanopisto/pyramus/rest/StudentRESTService.java
> +  @Path("/students/{STUDENTID:[0-9]*}/studentCard/{CARDID:[0-9]*}")
Koska opiskelijalla on aina vain yksi kortti (OneToOne) niin tekisin tämän ehkä ilman CARDID-parametria, koska oikea kortti on aina löydettävissä opiskelijan perusteella.

2024-04-10 05:27 UTC, aviljakaine commented on rest/src/main/java/fi/otavanopisto/pyramus/rest/StudentRESTService.java
> +  public Response findStudentCard(@PathParam("STUDENTID") Long studentId) {
Tähän voisi lisätä LoggedIn-annotaation kirjautumisen tsekkausta varten.

2024-04-10 05:27 UTC, aviljakaine commented on rest/src/main/java/fi/otavanopisto/pyramus/rest/StudentRESTService.java
> +  public Response updateStudentCardActive(@PathParam("STUDENTID") Long studentId, @PathParam("CARDID") Long cardId, Boolean active) {
Tähän voisi lisätä LoggedIn -annotaation kirjautumisen tsekkausta varten

2024-04-10 05:50 UTC, aviljakaine requested changes

2024-04-10 05:50 UTC, aviljakaine commented on pyramus/src/main/webapp/templates/students/editstudent.jsp
> +            <input type="hidden" name="studentCards" value="${studentCards[student.id]}"/>
Tämä vaikuttaisi turhalta, sitä ei ilmeisesti lueta EditStudentJSONControllerissa(?)

2024-04-18 04:49 UTC, pkukkon approved these changes
Seems okay to me.

2024-05-15 08:10 UTC, closed without merging