Slice: servlet + koko muu setti
otavanopisto/pyramus pull request #1580
Opened 2024-05-15 06:19 UTC by saaralepisto

Closes #1579

2024-05-15 12:00 UTC, aviljakaine requested changes
Pienehköjä siivouksia ja vähän pohdintaa.

ExpiryDaten ja cancellationDaten suhteesta listaukseen en oikein saa katselmoimalla kuvaa, voisin ehkä jossain välissä testata eri tilanteita tämän kanssa.

2024-05-15 12:00 UTC, aviljakaine commented on pyramus/src/main/webapp/templates/students/editstudent.jsp
> +                    <div id="emailTable.${student.id}"></div>
Meneekö tämän nimi päällekkäin opiskelijan tiedoissa olevien saman nimisen kentän kanssa? Tuo näytettäisiin alustettavan skriptillä, joten veikkaan, että jompikumpi taulukko ei toimi.

2024-05-15 12:00 UTC, aviljakaine commented on pyramus/src/main/webapp/templates/students/editstudent.jsp
> +                        <input type="checkbox" name="active.${student.id}" value="true"/>
Pystyikö kortin vaihtamaan CANCELLED-tilaan miten?

2024-05-15 12:00 UTC, aviljakaine commented on pyramus/src/main/webapp/templates/students/viewstudent.jsp
> +                      <c:choose>
CANCELLED-tila

2024-05-15 12:00 UTC, aviljakaine commented on pyramus/src/main/webapp/templates/students/editstudent.jsp
> +                        <input type="checkbox" name="active.${student.id}" value="true"/>
Ilmeisesti onkin tuolla JSONRequestControllerissa

2024-05-15 12:00 UTC, aviljakaine commented on pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/StudentCardServlet.java
> +    PrintWriter out = response.getWriter();
Menisiköhän tämä `response.getWriter()` suoraan ObjectMapperin `writeValue`:n parametriksi, pääsisi eroon tuosta StringWriterista kokonaan?

2024-05-15 12:00 UTC, aviljakaine commented on pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/StudentCardServlet.java
> +      fi.otavanopisto.pyramus.rest.model.StudentCard restModel = new fi.otavanopisto.pyramus.rest.model.StudentCard();
Sliceä varten on varmaan tehtävä erillinen "rest model", jossa on vain ne heidän tarvitsemat tiedot. Heillä ei ole tarvetta ainakaan noille id, userentityid, studyprogramme(?), activity -kentille. Dokkarissa taisi olla lista niistä.

Pitäisikö tuon expiryDate:n olla cancellationDate, jos kortti on peruutettu? Tai ehkä pienempi noista.

2024-05-15 12:00 UTC, aviljakaine commented on pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/StudentCardServlet.java
> +        cal.set(Calendar.DAY_OF_MONTH, cal.get(Calendar.DAY_OF_MONTH)-13);
Tähän on Calendar:ssa parempi metodi `cal.add(Calendar.DATE, -14);` Tämän pitäisi mennä aina loogisesti 14 päivää taaksepäin (kun arvo on negatiivinen).

`cal.setTime(new Date());` ylempänä on myös ylimääräinen, `Calendar.getInstance()` dokumentaation mukaan palauttaa aina nykyhetken.

2024-05-15 12:00 UTC, aviljakaine commented on pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/StudentCardServlet.java
> +      // Student cards with activity "cancelled" need still to be listed two weeks after cancellation
Jos muistan oikein niin myös "oikean" päättymispäivän jälkeen piti olla tuo 2vk aika, mutta ehkä hyvä tarkistaa.

2024-05-15 12:13 UTC, aviljakaine commented on pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/StudentCardServlet.java
> +@WebServlet("/studentCard")
Vaihtaisiko tämän osoitteen vielä, `/api/slice` tjsp?

2024-05-28 05:19 UTC, aviljakaine requested changes
Pari huomiota committiin, vilkaisen vielä paremmin.

2024-05-28 05:19 UTC, aviljakaine commented on rest/src/main/java/fi/otavanopisto/pyramus/rest/StudentRESTService.java
> +  public Response updateStudentCardActive(@PathParam("STUDENTID") Long studentId, Boolean active) {
Huomiona vain, että ainakin itse olisin sillä kannalla, että jos samassa polussa on useita metodeja, että ne toimisivat samalla payloadilla, eli jos GET palauttaa StudentCard:n, niin PUT ottaisi vastaavasti sen takaisin. Ehkä tällaisen "sisällä olevan" tiedon muuttaminen voisi olla eri polussa (esim /studentCard/active). Mutta ei nyt välttämätöntä muuttaa tähän.

2024-05-28 05:19 UTC, aviljakaine commented on pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/StudentCardServlet.java
> +      if (studentCard.getCancellationDate() != null && studentCard.getActivity().equals(StudentCardActivity.CANCELLED)) {
DAO listaa pelkän expirydate:n perusteella; meneeköhän tämä ok, kun tässä saatetaankin käyttää sitten eri päättymispäivämäärää?

2024-06-04 10:09 UTC, saaralepisto commented
closes #1545 
closes #1549

2024-06-04 11:17 UTC, pkukkon approved these changes

2024-06-05 06:26 UTC, merged