Yhteydenottomerkintojen massatallennus
otavanopisto/pyramus pull request #1601
Opened 2024-08-29 03:37 UTC by saaralepisto

closes #1595

2024-08-29 03:37 UTC, saaralepisto commented
https://github.com/otavanopisto/muikku/pull/7116

2024-09-06 12:47 UTC, aviljakaine requested changes
Hajatelmia

2024-09-06 12:47 UTC, aviljakaine commented on rest-model/src/main/java/fi/otavanopisto/pyramus/rest/model/StudentContactLogEntry.java
> +  private List<Long> recipients;
Koska tätä samaa luokkaa käytetään jo vanhastaan, niin tämä tulee nyt uutena kenttänä niihinkin ja saattaa hämätä niissä. Saattaisin tehdä itse niin, että periyttäisin tästä uuden "batch"-luokan, joka saisi periytymisen kautta nämä vanhat tiedot ja toisi tuon uuden recipients-listan siihen lisäksi. Luonnollisesti endpointtia pitää muuttaa ja varmaan objectfactoryyn tehdä myös oma käsittelijä.

2024-09-12 11:01 UTC, pkukkon requested changes

2024-09-12 11:01 UTC, pkukkon commented on rest/src/main/java/fi/otavanopisto/pyramus/rest/StudentRESTService.java
> +      cLE = (fi.otavanopisto.pyramus.rest.model.StudentContactLogWithRecipients) objectFactory.createModel(contactLogEntry);
Tässä voisi ihan suosiolla tehdä mitä ObjectFactoryssa tehtiin tyyliin...

```
cLE = new StudentContactLogWithRecipients(
  contactLogEntry.getId(),
  contactLogEntry.getText(),
  jne.
);
```

2024-09-12 11:18 UTC, aviljakaine commented on rest-model/src/main/java/fi/otavanopisto/pyramus/rest/model/StudentContactLogEntry.java
> +  private List<Long> recipients;
Eihän tuo ObjectFactory tietysti toimi tässä, kun on edelleen samasta Entitystä kyse, eli sen voi unohtaa. Muutoin kyllä noin periyttämällä voi tehdä tähän massa-tilanteeseen oman rest-modelin.

2024-09-13 08:17 UTC, pkukkon requested changes

2024-09-13 08:17 UTC, pkukkon commented on rest/src/main/java/fi/otavanopisto/pyramus/rest/StudentRESTService.java
> +      cLE.setEntryDate(entryDate);
I suppose the shortest Date to OffsetDateTime would be something like...

`OffsetDateTime.ofInstant(contactLogEntry.getEntryDate().toInstant(), ZoneId.systemDefault())`

2024-09-16 08:49 UTC, pkukkon approved these changes

2024-09-18 08:01 UTC, aviljakaine approved these changes

2024-09-25 06:02 UTC, merged